---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ingress-nginx-component
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/kubernetes/ingress-nginx
