---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mosquitto-mqtt-broker-component
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./broker/mosquitto/deployment/
  prune: true
  sourceRef:
    kind: GitRepository
    name: mqtt-component
  targetNamespace: mqtt
