---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: mqtt-web-client-component
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/s-h-a-p/mqtt-web-client-component
